# =====================================================================
# Server block gateway
# =====================================================================

server {
    listen 80;
    server_name _;

    access_log /dev/stdout json_combined;

    # =================================================================
    # REQUEST VALIDATION
    # Maximum request body = 1 MB
    # =================================================================
    client_max_body_size 1m;


    # =================================================================
    # Health check gateway sendiri
    # =================================================================

    location = /healthz {
        access_log off;
        return 200 "gateway ok\n";
    }


    # =================================================================
    # Metrics endpoint
    # =================================================================

    location = /metrics {
        access_log off;
        default_type application/json;
        return 200 '{"status":"ok","connections_active":$connections_active,"connections_reading":$connections_reading,"connections_writing":$connections_writing,"connections_waiting":$connections_waiting}';
    }


    # =================================================================
    # Banner root
    # =================================================================

    location = / {
        access_log off;
        default_type application/json;

        return 200 '{"gateway":"api-gateway-kelompok1","docs":"/api/"}';
    }


    # =================================================================
    # Route API
    # =================================================================

    include /etc/nginx/conf.d/routes/*.conf;


    # =================================================================
    # Fallback
    # =================================================================

    location / {
        return 404 '{"error":"not found"}';
    }
}
