# =====================================================================
# Server block gateway
# =====================================================================

server {
    listen 80;
    server_name _;

    # =================================================================
    # REQUEST VALIDATION
    # Maximum request body = 1 MB
    # =================================================================
    client_max_body_size 1m;

    # ---------- Health check gateway sendiri ----------
    location = /healthz {
        access_log off;
        return 200 "gateway ok\n";
    }

    # ---------- Banner root ----------
    location = / {
        access_log off;
        default_type application/json;
        return 200 '{"gateway":"api-gateway-kelompok1","docs":"/api/"}';
    }

    # ---------- Route API ----------
    include /etc/nginx/conf.d/routes/*.conf;

    # ---------- Fallback ----------
    location / {
        return 404 '{"error":"not found"}';
    }
}